### ISSUE TITLE
ゲーム本体のオプションの設定をOKするとフリーズする

### ISSUE THREAD

**Issue by rynan4818** [denpadokei/HttpSiraStatus#19]
ゲーム本体のオプションの設定(コントローラ調整など)をOKで閉じるとフリーズします。

動作環境はHttpSiraStatusが動く最低限環境で確認しました。

Game version 1.21.0 (Steam版)
Beat Saber IPA: 4.2.2
SiraUtil : 3.0.6
websocket-sharp : 1.0.4
HttpSiraStatus : 7.1.0

その時のログを添付します。
[_latest.log](https://github.com/denpadokei/HttpSiraStatus/files/8549850/_latest.log)

どうも、HttpSiraStatusの再起動処理が上手く行ってないみたいです。
ご確認をよろしくおねがいします。

**Comment by denpadokei** [comment]
報告ありがとうございます。
原因が分かったのですぐ修正します。
