### ISSUE TITLE
Game object "mode" exposing a different value in 1.22.0 Solo

### ISSUE THREAD

**Issue by reesypiece** [denpadokei/HttpSiraStatus#24]
I am sorry, my Japanese is not good enough to communicate, so I will report this bug in English.

Beat Saber version: 1.22.0
HTTPSiraStatus version: 7.1.4
BSIPA version: 4.2.2
websocket-sharp version: 1.0.4
Platform: Steam (launched with `-vrmode oculus`)

I am using a live streaming overlay that uses `game.mode` to obtain my best score on ScoreSaber. In versions 1.21.0 and older of Beat Saber, if I play a song in Solo, the value of `mode` in the `game` object shows `SoloStandard`. But, in 1.22.0, the value of `mode` in the `game` object will show as `SoloFreePlay` instead.

To compare the `game` objects between version 1.22 and earlier versions, I have attached an object sent after the `songStart` event with Beat Saber version 1.22/HttpSiraStatus 7.1.4 ([httpsira122.txt](https://github.com/denpadokei/HttpSiraStatus/files/8665357/httpsira122.txt)) and Beat Saber version 1.19/HttpSiraStatus 6.1.2 ([httpsira119.txt](https://github.com/denpadokei/HttpSiraStatus/files/8665368/httpsira119.txt)).

**Comment by denpadokei** [comment]
Thanks for the report.
The game.mode is obsolete under the fork.
Therefore, we had planned to abolish it here as well, but instead we have changed it to separate the modes into smaller ones.
- SoloFreePlay
- Party
- BeatmapEditor
- SoloCampaign
- FloorAdjust
- Quit
- Multiplayer
- Options
- HowToPlay

Please check the isuue below for the history of how it was discontinued.
https://github.com/opl-/beatsaber-http-status/issues/84
However, you can turn SoloFreePlay into SoloStandard if you still want to use this value.

**Comment by reesypiece** [comment]
Thank you for your response!

In ScoreSaber, map game mode is stored as `Solo<characteristic>` (for example, [the leaderboards for this map](https://scoresaber.com/leaderboard/429617)), which is why my streaming overlay uses `game.mode`. 

If I am reading the issue you linked correctly, `game.mode` is still present for backwards compatibility, but it is deprecated and obsolete. `beatmap.characteristic` in this fork is closer to what I am looking for. 

But, `beatmap.characteristic` has an extra space at the end, so it looks like `beatmap."characteristic "` when it is exposed. ([line here](https://github.com/denpadokei/HttpSiraStatus/blob/f5b880a67efbdf769c95c9df169d08890e933e40/HttpSiraStatus/Models/StatusManager.cs#L183))

**Comment by denpadokei** [comment]
The extra space is a bug. This will be fixed.

Do you think we should change the `game.mode` back to be backward compatible with older versions?
Or use `beatmap.characteristic` and generate the characters in the overlay?

**Comment by reesypiece** [comment]
I believe the [implementation](https://github.com/opl-/beatsaber-http-status/commit/544eca3263b3c22a88ad8f733159faddc55ef740) in beatsaber-http-status is okay. Keep `game.mode`, but generate it with `beatmap.characteristic` for backwards compatibility.

**Comment by denpadokei** [comment]
The `game.mode` display has been restored to the original as in the forked original.
