### ISSUE TITLE
Compatibility issue with ACC Campaign

### ISSUE THREAD

**Issue by Morgolf** [denpadokei/HttpSiraStatus#32]
## Current behavior

It seems that HttpSiraStatus causes an issue where [custom ACC Campaign](https://github.com/accsaber/ACC-Campaign/releases/tag/1.0.4) does not recognize score properly, the game in the campaign instead thinks that the player is at 100% all the time no matter how good or bad they are doing in a map. ACC community already noticed that removing HttpSiraStatus fixes the issue so thats the reason I am posting this bug report here, maybe that is something that could be fixed in HttpSiraStatus.

## Expected behavior

ACC campaign should recognize the score properly with HttpSiraStatus installed.

## Reproduction steps

1. Launch BS in 1.24. with ACC-Campaign 1.0.4. and HttpSiraStatus 8.0.0.
2. Open Custom Campaigns mod and select ACC Campaign
3. Start any map in Custom Campaign
4. Hit bloqs for less than 115 and observe the score

## Environment

BeatSaber version: 1.24.
HTTP Status version: 8.0.0.
Platform: (Vive, Oculus, other?) steamVR (Index)
[_latest.log](https://github.com/denpadokei/HttpSiraStatus/files/9335915/_latest.log)

**Comment by denpadokei** [comment]
Thanks for the report.
I have taken measures to prevent interference.
