### ISSUE TITLE
3.0.0 boost events missing

### ISSUE THREAD

**Issue by codingcatgirl** [denpadokei/HttpSiraStatus#34]
## Current behavior
Boost events in 3.0.0 maps are not being sent.

## Expected behavior
boost events in 3.0.0 maps should be sent (according [to this line of code](https://github.com/denpadokei/HttpSiraStatus/blob/8.0.0/HttpSiraStatus/Models/V3BeatmapEventInfomation.cs#L111))

## Reproduction steps
1. Install everything
2. Connect via Websocket
3. Start the Song "Magic" from OST 5.
4. Note that boost events are not being transmitted.

## Environment
Newest Beat Saber version, newest released plugin version (8.0.1).

**Comment by denpadokei** [comment]
Thank you for your report.
I will investigate.

**Comment by denpadokei** [comment]
Correction finished.

**Comment by codingcatgirl** [comment]
Wow, that was quick. Thank you!
