### ISSUE TITLE
NaN present in JSON

### ISSUE THREAD

**Issue by TakingFire** [denpadokei/HttpSiraStatus#38]
## Current behavior
Some older beatmaps produce a message containing `NaN` in the Performance object.
In this example, `multiplierProgress`:
```json
{"status":{"performance":{"currentSongTime":10,"relativeScore":0.886956512928009,"multiplier":0,"combo":4,"maxCombo":4,"currentMaxScore":0,"lastNoteScore":0,"hitNotes":4,"missedNotes":0,"rank":"S","passedBombs":0,"softFailed":false,"rawScore":0,"batteryEnergy":null,"passedNotes":4,"score":0,"hitBombs":0,"multiplierProgress":NaN,"energy":0.539999961853027}},"time":1662254394851,"event":"scoreChanged"}
```
This is invalid JSON and can cause issues with parsing.

## Expected behavior
`NaN` is replaced with `null` or `0` to keep the JSON valid.

## Reproduction steps
1. Start an old map (for example: https://beatsaver.com/maps/45)
2. Catch any socket message containing the Performance object
3. Attempt to parse JSON

## Environment

BeatSaber version: 1.24.1
HTTP Status version: 8.0.2
Platform: SteamVR, Windows

**Comment by denpadokei** [comment]
Thank you for your report.
Start investigating.

**Comment by denpadokei** [comment]
The problem did not reproduce.
Could you upload the log when the phenomenon occurred?
(InstDir)/Logs

**Comment by TakingFire** [comment]
On further testing, it only occurs when viewing Replays. I believe it may be old *replays*, rather than old *levels*.
Here is the [_latest.log](https://github.com/denpadokei/HttpSiraStatus/files/9484115/_latest.log), it contains two song replays that both cause the issue.

Here is also my replay file for https://beatsaver.com/maps/45, if it is useful:
[76561198257862880-Give It Up-9BCFBD06C6CEAC3E4FF44093FBC33AB83587108B.zip](https://github.com/denpadokei/HttpSiraStatus/files/9484130/76561198257862880-Give.It.Up-9BCFBD06C6CEAC3E4FF44093FBC33AB83587108B.zip)

**Comment by denpadokei** [comment]
It seems to be by design that multiplierProgress returns incorrect values with old replay data.
Make HTTPSiraStatus always return 0 instead of NaN.

Could you please test this DLL and confirm that 0 is returned?
[HttpSiraStatus-8.0.3-rc1-bs1.21.0-b844f89.zip](https://github.com/denpadokei/HttpSiraStatus/files/9484249/HttpSiraStatus-8.0.3-rc1-bs1.21.0-b844f89.zip)

**Comment by TakingFire** [comment]
I still appear to be getting `Nan` for `multiplierProgress`.
Demonstration video:

https://user-images.githubusercontent.com/38340654/188304737-69d63d9c-e3dd-4d5f-8be3-3b4ebb824117.mp4

**Comment by denpadokei** [comment]
[HttpSiraStatus-8.0.3-rc2-bs1.21.0-074797c.zip](https://github.com/denpadokei/HttpSiraStatus/files/9484333/HttpSiraStatus-8.0.3-rc2-bs1.21.0-074797c.zip)
Here is the output of the performance as a log.
Could you upload the output log after playing the NaN replay here?

**Comment by TakingFire** [comment]
This version works perfectly, here's the [log](https://github.com/denpadokei/HttpSiraStatus/files/9484355/_latest.log) showing it is 0 now. I'm not sure why the other _.dll_ didn't work.
Many of the older replays were giving invalid JSON, so it's great to see it working properly now!

**Comment by denpadokei** [comment]
thank you for making sure
I release this version.

Since the implementation of the replay function is a black box, it is difficult for me to deal with it any further.
You'll probably need to contact the ScoreSaber team, but your proposal will probably be rejected because the results and effort you're getting aren't worth it.
