### ISSUE TITLE
(v2) Boost events missing

### ISSUE THREAD

**Issue by TakingFire** [denpadokei/HttpSiraStatus#47]
## Current behavior
Boost events are not being sent for maps using v2 lighting.
`beatmap.color.environmentXBoost` are working properly, however the beatmapEvent is not being sent.

## Expected behavior
On a boost event, a beatmapEvent is sent with `{ type: 5, value: 0/1 }`.

## Reproduction steps
1. Run a song with custom boost colors ([example 1](https://beatsaver.com/maps/1bb86), [example 2](https://beatsaver.com/maps/2c73c))
2. Listen for beatmap events with type 5 (boost), see the [event reference](https://github.com/Caeden117/ChroMapper/blob/master/Assets/__Scripts/Map/Events/MapEvent.cs).
3. Find that no events are sent on color change.

## Environment

BeatSaber version: 1.28.0
HTTP Status version: 9.0.3
Platform: SteamVR, Windows

**Comment by denpadokei** [comment]
Thank you for the issue.
I will check and fix it soon.

**Comment by denpadokei** [comment]
Sorry, I forgot to update the docs when I fixed the V3 map event.

The current beatmapEvent has been completely replaced to support V3 maps.
The JSON for colorboost looks like this.
```json
{
	"time": 1678700059306,
	"event": "beatmapEvent",
	"beatmapEvent": {
		"version": "3.0.0",
		"boostColorsAreOn": false,
		"executionOrder": -100,
		"time": 0,
		"type": 2,
		"previousSameTypeEventData": {
			"time": 0,
			"executionOrder": 0,
			"version": "3.0.0",
			"type": 0
		},
		"nextSameTypeEventData": {
			"time": 89.386360168457,
			"executionOrder": -100,
			"version": "3.0.0",
			"boostColorsAreOn": true,
			"type": 2
		}
	}
}
```
The type at the time of V3 map is as follows.
```CSharp
public enum V3BeatmapEventType
{
    Unknown = 0,
    BPM = 1,
    ColorBoost = 2,
    LightColor = 3,
    LightRotation = 4,
    SpawnRotation = 5
}
```
Other updates will update protocol.md, so please wait a moment.


The events of the V2 map so far are as follows.
The `type` at this time will be Chromapper compliant.
```json
{
	"time": 1678700059306,
	"event": "beatmapEvent",
	"beatmapEvent": {
		"value": 0,
		"floatValue": 1,
		"version": "2.6.0",
		"executionOrder": -100,
		"time": 0,
		"type": 0,
		"previousSameTypeEventData": {
			"time": 0,
			"executionOrder": 0,
			"value": 0,
			"version": "2.6.0",
			"type": 0,
			"floatValue": 0
		},
		"nextSameTypeEventData": {
			"time": 2.18181824684143,
			"executionOrder": -100,
			"value": 3,
			"version": "2.6.0",
			"type": 0,
			"floatValue": 1
		}
	}
}
```

**Comment by TakingFire** [comment]
Thank you for the examples! I was unaware of the `boostColorsAreOn` key.
Testing the songs I mentioned, everything is updating as expected.

<img src="https://user-images.githubusercontent.com/38340654/224805115-81de344e-670d-4461-be4f-38f84eed807c.gif" width="300">
Including the type 5 event might be unnecessary as long as this method exists.
