### ISSUE TITLE
BeatSaber 1.37.3では再ビルドが必要です

### ISSUE THREAD

**Issue by rynan4818** [denpadokei/HttpSiraStatus#62]
BeatSaber 1.37.2→1.37.3でBeatmapDataItem.subtypeIdentifierがフィールドからプロパティに変更になったので、
`Could not find field in class`になります。再ビルドすれば1.37.3で動作するようになりました。

1.37.3はレガシーで残らないですね。このままクローズしてもらって構いません。

![image](https://github.com/user-attachments/assets/b61df936-5f50-4b69-a0da-c090604da22f)
![image](https://github.com/user-attachments/assets/ac2b712d-125f-40a7-b5dc-3a596285cdd0)
![image](https://github.com/user-attachments/assets/cdc49474-7363-4589-a172-7a83fdf07a23)

**Comment by denpadokei** [comment]
レガシーが1.37.3がないためマージせずにクローズします。
次回の更新にて対応します。
